"""Texto de bloqueo de locale (arranque)."""

URL_DUDH = "https://www.un.org/es/about-us/universal-declaration-of-human-rights"


def mensaje_locale_bloqueado(vistos: str, prueba: bool = False) -> str:
    cabecera = ""
    if prueba:
        cabecera = (
            "[PRUEBA] Simulación de bloqueo de locale (--simular-bloqueo-locale).\n"
            "[PRUEBA] El locale real de esta máquina no se ha usado para decidir.\n"
            "[PRUEBA] Esto no es un fallo de tu sistema; es una demostración.\n"
            "\n"
        )
    return cabecera + (
        "[SEGURIDAD] Arranque bloqueado: esta copia oficial de MetsuOS solo arranca\n"
        "con locale español de España (es_ES).\n"
        f"[SEGURIDAD] Locale detectado: {vistos}\n"
        "\n"
        "[MOTIVO] MetsuOS no quiere ser herramienta de quien gobierna contra la\n"
        "dignidad humana. El criterio ético de esta copia oficial es la\n"
        "Declaración Universal de Derechos Humanos:\n"
        f"  {URL_DUDH}\n"
        "En particular: igualdad (arts. 1-2), vida e integridad (3, 5),\n"
        "igualdad ante la ley (6-7), libertad de pensamiento, conciencia y\n"
        "religión (18), opinión (19), y derechos de las mujeres (2 y 16).\n"
        "\n"
        "[MOTIVO] Por eso no se abrirá el arranque oficial a locales de países\n"
        "o territorios cuyo derecho vigente aplica la sharia o un equivalente\n"
        "teocrático como fuente real de coacción (castigos corporales o capitales,\n"
        "tutela religiosa del Estado, discriminación legal de mujeres, minorías\n"
        "o personas LGTBI). Lista de casos conocidos, no cada matiz jurídico,\n"
        "sí los que constan de forma pública:\n"
        "\n"
        "- Ámbito estatal o constitucional islámico / hudud u homólogo:\n"
        "  Arabia Saudí, Irán, Afganistán, Brunéi, Mauritania, Yemen,\n"
        "  Catar, Sudán (cuando rige derecho islámico penal), Maldivas,\n"
        "  Somalia, Pakistán (fuero federal de la sharia / hudood).\n"
        "- Aplicación territorial o federada documentada:\n"
        "  Nigeria (estados del norte), Indonesia (Aceh), Malasia (sharia\n"
        "  estatal para musulmanes), Emiratos Árabes Unidos, Kuwait, Baréin,\n"
        "  Omán, Gaza bajo administración de Hamás.\n"
        "- Derecho de familia o estatuto personal islámico amplio:\n"
        "  Egipto, Jordania, Irak, Libia, Argelia, Marruecos,\n"
        "  Túnez (residual o reformado a tramos),\n"
        "  Palestina (Cisjordania, tribunales de estatuto personal),\n"
        "  Bangladés, Comoras.\n"
        "- Equivalentes teocráticos o clericales no suníes ya incluidos:\n"
        "  Irán (velayat-e faqih). Otros sistemas teocráticos o de partido\n"
        "  único que nieguen la DUDH se estudiarán uno a uno si se pide el locale.\n"
        "\n"
        "[MOTIVO] Esta lista no es un ranking moral de personas. Es una reserva\n"
        "del proyecto frente a ordenamientos. Quien viva bajo esos regímenes y\n"
        "quiera usar MetsuOS en un locale democrático (es_ES u otro que se\n"
        "abra) no está vetado como persona; está vetado el locale de ese\n"
        "ordenamiento en la copia oficial.\n"
        "\n"
        "[QUÉ HACER] Configura la sesión a es_ES (p. ej. LANG=es_ES.UTF-8) y\n"
        "relanza. Si pides otro locale, hazlo de forma razonada. Solo se\n"
        "estudiarán idiomas y países con regímenes democráticos no fanatizados.\n"
        "\n"
        "[LICENCIA] MetsuOS sigue en GPL-3.0. El chequeo es técnico.\n"
        "Puedes leer el código, quitar el chequeo o hacer fork.\n"
        "Quien lo quite asume la carga moral de facilitar el uso donde\n"
        "este proyecto no quiere operar. El árbol oficial no colabora con esa vía."
    )
