[tool.poetry]
name = "metsuos"
version = "0.1.0"
description = "MetsuOS: Sistema Operativo simulado y modular"
authors = ["Metsuke"]
homepage = "https://metsuke.com"
readme = "README.md"
packages = [
    { include = "moslib" }
]

[tool.poetry.dependencies]
python = "^3.10"
# Aquí podrás añadir joblib, cachetools o cualquier otra que necesites en el futuro:
# joblib = "^1.3.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"