[tool.poetry]
name = "metsuos"
version = "0.2.2"
description = "MetsuOS: Sistema Operativo simulado y modular"
authors = ["Metsuke"]
homepage = "https://metsuke.com"
readme = "README.md"
packages = [
    { include = "moslib" }
]

[tool.poetry.dependencies]
python = "^3.10"
pytest = "^8.3.0"
pytest-cov = "^5.0.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_functions = ["test_*"]
addopts = "-v --tb=short"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"